### PR TITLE
Bundle client JS with browserify

### PR DESCRIPTION
**Pull request by alexbasalyga**
I added an npm script that bundles `app/node_modules/client/index.js` into `app/node_modules/public/js/bundle.js`.

### CODE REVIEW

**Comment by ericelliott** [comment]
Good start.

We need to make a source map, too and make sure that the browserify step is added to the build.

**Comment by alexbasalyga** [comment]
No problem. I'll handle that and submit another PR.

**Comment by ericelliott** [comment]
Awesome! =)

**Comment by alexbasalyga** [comment]
We'll only want source maps in development (i.e., not in production). So I think the right way to approach this is to split the `build` npm script into two scripts: `build` and `build-dev`. It then seems prudent to isolate the git hash commands into their own script to reduce redundancy, `build-hash`. I implemented this [here](https://github.com/alexbasalyga/isomorphic-express-boilerplate/commit/5ea9e6cf93e100738259b9ed6ba7c127e75b035e). Let me know if this works for you and I'll submit the PR.

**Comment by ericelliott** [comment]
Are you sure we only want source maps in dev? Check out [the compile step](https://github.com/ericelliott/todotasks/blob/master/implementations/npm/package.json#L11) from the npm implementation in todotasks.

It splits the source maps into separate files that only need to be loaded when you open the developer console. That way we can have source maps in dev & prod without bogging users down with sourcemaps overhead.

**Comment by alexbasalyga** [comment]
Interesting. I never realized that source maps aren't fetched unless the dev console is open. Great tip. See #14.

**Pull request merged**
