### PR TITLE
Remove x-powered-by

### PR DESCRIPTION
**Pull request by alexbasalyga**
http://expressjs.com/api.html#app.disable  
http://expressjs.com/api.html#app.settings.table

### CODE REVIEW

**Comment by ericelliott** [comment]
Awesome!

**Comment by ericelliott** [comment]
Looks great!

**Comment by ericelliott** [comment]
Thanks for your help. I've added a unit test for it and added you as a collaborator to the repo. =)

**Comment by alexbasalyga** [comment]
Thanks, Eric! I was initially conflicted about writing a test for this since the Express team have a [test for the app.disable method](https://github.com/strongloop/express/blob/112dbb2ab40a6ecdd7ed0de4503dfc56655a24a3/test/config.js#L84-L90) and there's no functional code here outside of calling the method on the 'x-powered-by' setting, but upon further consideration I do think it's worth having a test to ensure the local implementation is correct and working.

**Comment by ericelliott** [comment]
:+1: 

If you want to keep helping, I've written up [a roadmap](https://github.com/ericelliott/isomorphic-express-boilerplate/issues/4).

**Pull request merged**
